title: CanIWebView
repository: WebView-CG/Compatibility-Data-Project
baseurl: /Compatibility-Data-Project/ 

collections:
  posts:
    output: true
    permalink: /Compatibility-Data-Project/news/:year-:month-:day-:title/
  features:
    output: true
  generated_features:
    output: true
    permalink: /Compatibility-Data-Project/features/:name/
  clients:
    output: true

defaults:
  - scope:
      path: ""
      type: "features"
    values:
      layout: "feature"
  - scope:
      path: ""
      type: "generated_features"
    values:
      layout: "feature"
  - scope:
      path: ""
      type: "clients"
    values:
      layout: "client"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

permalink: /Compatibility-Data-Project/:title/

plugins:
  - jekyll-mentions
  - jekyll-github-metadata
  - jekyll-default-layout

sass:
  style: compact

exclude: [vendor, "tools/update_bcd_version.py", "Gemfile", "Gemfile.lock", "CONTRIBUTING.md", "LICENSE", "README.md", "bcd_version", ".github"]
include: ["_js"]
